name: Smart LeetCode Checker

on:
  push:

jobs:

  check-code:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3


    # ---------- C++ CHECK ----------

    - name: Compile C++
      run: |
        find . -name "*.cpp" -exec g++ {} \;


    # ---------- JAVA CHECK ----------

    - name: Compile Java
      run: |
        find . -name "*.java" -exec javac {} \;


    # ---------- PYTHON SYNTAX CHECK ----------

    - name: Python Compile Check
      run: |
        python3 -m py_compile $(find . -name "*.py")


    # ---------- PYTHON ADVANCED CHECK ----------

    - name: Install Flake8
      run: |
        pip install flake8

    - name: Run Flake8
      run: |
        flake8 .
